name = "SeisSolXDMF"
uuid = "fc3049fc-4624-4ea9-a8a9-22daae44174f"
authors = ["Maximilian Schmeller <m.schmeller@tum.de>"]
version = "1.0.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"
